<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/courses.php');
	include_once(__DIR__ . '/courses_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('courses');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'courses';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`courses`.`id`" => "id",
		"`courses`.`faculty_name`" => "faculty_name",
		"`courses`.`faculty_photo`" => "faculty_photo",
		"if(CHAR_LENGTH(`courses`.`faculty_description`)>100, concat(left(`courses`.`faculty_description`,100),' ...'), `courses`.`faculty_description`)" => "faculty_description",
		"`courses`.`contact`" => "contact",
		"`courses`.`email`" => "email",
		"`courses`.`location_google_map_key`" => "location_google_map_key",
		"`courses`.`syllabus`" => "syllabus",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`courses`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => '`courses`.`contact`',
		6 => 6,
		7 => 7,
		8 => 8,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`courses`.`id`" => "id",
		"`courses`.`faculty_name`" => "faculty_name",
		"`courses`.`faculty_photo`" => "faculty_photo",
		"`courses`.`faculty_description`" => "faculty_description",
		"`courses`.`contact`" => "contact",
		"`courses`.`email`" => "email",
		"`courses`.`location_google_map_key`" => "location_google_map_key",
		"`courses`.`syllabus`" => "syllabus",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`courses`.`id`" => "ID",
		"`courses`.`faculty_name`" => "Faculty name",
		"`courses`.`faculty_description`" => "Faculty description",
		"`courses`.`contact`" => "Contact",
		"`courses`.`email`" => "Email",
		"`courses`.`location_google_map_key`" => "Google map iframe",
		"`courses`.`syllabus`" => "Syllabus",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`courses`.`id`" => "id",
		"`courses`.`faculty_name`" => "faculty_name",
		"`courses`.`faculty_description`" => "Faculty description",
		"`courses`.`contact`" => "contact",
		"`courses`.`email`" => "email",
		"`courses`.`location_google_map_key`" => "location_google_map_key",
		"`courses`.`syllabus`" => "syllabus",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`courses` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 40;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'courses_view.php';
	$x->TableTitle = 'Courses';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`courses`.`id`';
	$x->DefaultSortField = '2';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Faculty name', 'Faculty photo', 'Faculty description', 'Contact', 'Email', 'Google map iframe', 'Syllabus', ];
	$x->ColFieldName = ['faculty_name', 'faculty_photo', 'faculty_description', 'contact', 'email', 'location_google_map_key', 'syllabus', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, 8, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/courses_templateTV.html';
	$x->SelectedTemplate = 'templates/courses_templateTVS.html';
	$x->TemplateDV = 'templates/courses_templateDV.html';
	$x->TemplateDVP = 'templates/courses_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: courses_init
	$render = true;
	if(function_exists('courses_init')) {
		$args = [];
		$render = courses_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: courses_header
	$headerCode = '';
	if(function_exists('courses_header')) {
		$args = [];
		$headerCode = courses_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: courses_footer
	$footerCode = '';
	if(function_exists('courses_footer')) {
		$args = [];
		$footerCode = courses_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
