<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/soe_gallery.php');
	include_once(__DIR__ . '/soe_gallery_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('soe_gallery');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'soe_gallery';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`soe_gallery`.`id`" => "id",
		"if(CHAR_LENGTH(`soe_gallery`.`event_name`)>40, concat(left(`soe_gallery`.`event_name`,40),' ...'), `soe_gallery`.`event_name`)" => "event_name",
		"`soe_gallery`.`year`" => "year",
		"`soe_gallery`.`file_photo`" => "file_photo",
		"`soe_gallery`.`file_video`" => "file_video",
		"`soe_gallery`.`youtube_link`" => "youtube_link",
		"`soe_gallery`.`year_calendar`" => "year_calendar",
		"`soe_gallery`.`description`" => "description",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`soe_gallery`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`soe_gallery`.`id`" => "id",
		"`soe_gallery`.`event_name`" => "event_name",
		"`soe_gallery`.`year`" => "year",
		"`soe_gallery`.`file_photo`" => "file_photo",
		"`soe_gallery`.`file_video`" => "file_video",
		"`soe_gallery`.`youtube_link`" => "youtube_link",
		"`soe_gallery`.`year_calendar`" => "year_calendar",
		"`soe_gallery`.`description`" => "description",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`soe_gallery`.`id`" => "Id",
		"`soe_gallery`.`event_name`" => "Event name",
		"`soe_gallery`.`year`" => "Year",
		"`soe_gallery`.`file_video`" => "File video",
		"`soe_gallery`.`youtube_link`" => "Youtube link",
		"`soe_gallery`.`year_calendar`" => "Education calendar",
		"`soe_gallery`.`description`" => "Description",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`soe_gallery`.`id`" => "id",
		"`soe_gallery`.`event_name`" => "Event name",
		"`soe_gallery`.`year`" => "year",
		"`soe_gallery`.`file_video`" => "file_video",
		"`soe_gallery`.`youtube_link`" => "youtube_link",
		"`soe_gallery`.`year_calendar`" => "year_calendar",
		"`soe_gallery`.`description`" => "description",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`soe_gallery` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'soe_gallery_view.php';
	$x->TableTitle = 'Soe Gallery';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`soe_gallery`.`id`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Id', 'Event name', 'Year', 'File photo', 'File video', 'Youtube link', 'Education calendar', 'Description', ];
	$x->ColFieldName = ['id', 'event_name', 'year', 'file_photo', 'file_video', 'youtube_link', 'year_calendar', 'description', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/soe_gallery_templateTV.html';
	$x->SelectedTemplate = 'templates/soe_gallery_templateTVS.html';
	$x->TemplateDV = 'templates/soe_gallery_templateDV.html';
	$x->TemplateDVP = 'templates/soe_gallery_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: soe_gallery_init
	$render = true;
	if(function_exists('soe_gallery_init')) {
		$args = [];
		$render = soe_gallery_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: soe_gallery_header
	$headerCode = '';
	if(function_exists('soe_gallery_header')) {
		$args = [];
		$headerCode = soe_gallery_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: soe_gallery_footer
	$footerCode = '';
	if(function_exists('soe_gallery_footer')) {
		$args = [];
		$footerCode = soe_gallery_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
