<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/soe_posts.php');
	include_once(__DIR__ . '/soe_posts_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('soe_posts');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'soe_posts';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`soe_posts`.`id`" => "id",
		"if(CHAR_LENGTH(`soe_posts`.`title`)>40, concat(left(`soe_posts`.`title`,40),' ...'), `soe_posts`.`title`)" => "title",
		"if(CHAR_LENGTH(`soe_posts`.`tags`)>40, concat(left(`soe_posts`.`tags`,40),' ...'), `soe_posts`.`tags`)" => "tags",
		"IF(    CHAR_LENGTH(`category1`.`category_name`), CONCAT_WS('',   `category1`.`category_name`), '') /* Category */" => "category",
		"if(`soe_posts`.`date`,date_format(`soe_posts`.`date`,'%m/%d/%Y'),'')" => "date",
		"if(CHAR_LENGTH(`soe_posts`.`content`)>100, concat(left(`soe_posts`.`content`,100),' ...'), `soe_posts`.`content`)" => "content",
		"`soe_posts`.`file_name`" => "file_name",
		"`soe_posts`.`photo`" => "photo",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`soe_posts`.`id`',
		2 => 2,
		3 => 3,
		4 => '`category1`.`category_name`',
		5 => '`soe_posts`.`date`',
		6 => 6,
		7 => 7,
		8 => 8,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`soe_posts`.`id`" => "id",
		"`soe_posts`.`title`" => "title",
		"`soe_posts`.`tags`" => "tags",
		"IF(    CHAR_LENGTH(`category1`.`category_name`), CONCAT_WS('',   `category1`.`category_name`), '') /* Category */" => "category",
		"if(`soe_posts`.`date`,date_format(`soe_posts`.`date`,'%m/%d/%Y'),'')" => "date",
		"`soe_posts`.`content`" => "content",
		"`soe_posts`.`file_name`" => "file_name",
		"`soe_posts`.`photo`" => "photo",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`soe_posts`.`id`" => "Id",
		"`soe_posts`.`title`" => "Title",
		"`soe_posts`.`tags`" => "Tags",
		"IF(    CHAR_LENGTH(`category1`.`category_name`), CONCAT_WS('',   `category1`.`category_name`), '') /* Category */" => "Category",
		"`soe_posts`.`date`" => "Date",
		"`soe_posts`.`content`" => "Content",
		"`soe_posts`.`file_name`" => "File name",
		"`soe_posts`.`photo`" => "Photo",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`soe_posts`.`id`" => "id",
		"`soe_posts`.`title`" => "Title",
		"`soe_posts`.`tags`" => "Tags",
		"IF(    CHAR_LENGTH(`category1`.`category_name`), CONCAT_WS('',   `category1`.`category_name`), '') /* Category */" => "category",
		"if(`soe_posts`.`date`,date_format(`soe_posts`.`date`,'%m/%d/%Y'),'')" => "date",
		"`soe_posts`.`content`" => "Content",
		"`soe_posts`.`file_name`" => "file_name",
		"`soe_posts`.`photo`" => "photo",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['category' => 'Category', ];

	$x->QueryFrom = "`soe_posts` LEFT JOIN `category` as category1 ON `category1`.`id`=`soe_posts`.`category` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'soe_posts_view.php';
	$x->TableTitle = 'Soe posts';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`soe_posts`.`id`';
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Id', 'Title', 'Tags', 'Category', 'Date', 'Content', 'File name', 'Photo', ];
	$x->ColFieldName = ['id', 'title', 'tags', 'category', 'date', 'content', 'file_name', 'photo', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 8, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/soe_posts_templateTV.html';
	$x->SelectedTemplate = 'templates/soe_posts_templateTVS.html';
	$x->TemplateDV = 'templates/soe_posts_templateDV.html';
	$x->TemplateDVP = 'templates/soe_posts_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: soe_posts_init
	$render = true;
	if(function_exists('soe_posts_init')) {
		$args = [];
		$render = soe_posts_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: soe_posts_header
	$headerCode = '';
	if(function_exists('soe_posts_header')) {
		$args = [];
		$headerCode = soe_posts_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: soe_posts_footer
	$footerCode = '';
	if(function_exists('soe_posts_footer')) {
		$args = [];
		$footerCode = soe_posts_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
