<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/notes.php');
	include_once(__DIR__ . '/notes_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('notes');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'notes';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`notes`.`id`" => "id",
		"`notes`.`name`" => "name",
		"IF(    CHAR_LENGTH(`notes_category1`.`notes_category`), CONCAT_WS('',   `notes_category1`.`notes_category`), '') /* Category */" => "category",
		"IF(    CHAR_LENGTH(`staffs1`.`name`), CONCAT_WS('',   `staffs1`.`name`), '') /* Uploaded by */" => "uploaded_by",
		"`notes`.`description`" => "description",
		"`notes`.`photo`" => "photo",
		"`notes`.`file_one`" => "file_one",
		"`notes`.`file_two`" => "file_two",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`notes`.`id`',
		2 => 2,
		3 => '`notes_category1`.`notes_category`',
		4 => '`staffs1`.`name`',
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`notes`.`id`" => "id",
		"`notes`.`name`" => "name",
		"IF(    CHAR_LENGTH(`notes_category1`.`notes_category`), CONCAT_WS('',   `notes_category1`.`notes_category`), '') /* Category */" => "category",
		"IF(    CHAR_LENGTH(`staffs1`.`name`), CONCAT_WS('',   `staffs1`.`name`), '') /* Uploaded by */" => "uploaded_by",
		"`notes`.`description`" => "description",
		"`notes`.`photo`" => "photo",
		"`notes`.`file_one`" => "file_one",
		"`notes`.`file_two`" => "file_two",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`notes`.`id`" => "ID",
		"`notes`.`name`" => "Name",
		"IF(    CHAR_LENGTH(`notes_category1`.`notes_category`), CONCAT_WS('',   `notes_category1`.`notes_category`), '') /* Category */" => "Category",
		"IF(    CHAR_LENGTH(`staffs1`.`name`), CONCAT_WS('',   `staffs1`.`name`), '') /* Uploaded by */" => "Uploaded by",
		"`notes`.`description`" => "Description",
		"`notes`.`file_one`" => "File one",
		"`notes`.`file_two`" => "File two",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`notes`.`id`" => "id",
		"`notes`.`name`" => "name",
		"IF(    CHAR_LENGTH(`notes_category1`.`notes_category`), CONCAT_WS('',   `notes_category1`.`notes_category`), '') /* Category */" => "category",
		"IF(    CHAR_LENGTH(`staffs1`.`name`), CONCAT_WS('',   `staffs1`.`name`), '') /* Uploaded by */" => "uploaded_by",
		"`notes`.`description`" => "description",
		"`notes`.`file_one`" => "file_one",
		"`notes`.`file_two`" => "file_two",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['category' => 'Category', 'uploaded_by' => 'Uploaded by', ];

	$x->QueryFrom = "`notes` LEFT JOIN `notes_category` as notes_category1 ON `notes_category1`.`id`=`notes`.`category` LEFT JOIN `staffs` as staffs1 ON `staffs1`.`id`=`notes`.`uploaded_by` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'notes_view.php';
	$x->TableTitle = 'Notes';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`notes`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Name', 'Category', 'Uploaded by', 'Description', 'Photo', 'File one', 'File two', ];
	$x->ColFieldName = ['name', 'category', 'uploaded_by', 'description', 'photo', 'file_one', 'file_two', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, 8, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/notes_templateTV.html';
	$x->SelectedTemplate = 'templates/notes_templateTVS.html';
	$x->TemplateDV = 'templates/notes_templateDV.html';
	$x->TemplateDVP = 'templates/notes_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: notes_init
	$render = true;
	if(function_exists('notes_init')) {
		$args = [];
		$render = notes_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: notes_header
	$headerCode = '';
	if(function_exists('notes_header')) {
		$args = [];
		$headerCode = notes_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: notes_footer
	$footerCode = '';
	if(function_exists('notes_footer')) {
		$args = [];
		$footerCode = notes_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
