<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/staffs.php');
	include_once(__DIR__ . '/staffs_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('staffs');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'staffs';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`staffs`.`id`" => "id",
		"if(CHAR_LENGTH(`staffs`.`name`)>40, concat(left(`staffs`.`name`,40),' ...'), `staffs`.`name`)" => "name",
		"if(CHAR_LENGTH(`staffs`.`title`)>40, concat(left(`staffs`.`title`,40),' ...'), `staffs`.`title`)" => "title",
		"`staffs`.`photo`" => "photo",
		"`staffs`.`description`" => "description",
		"`staffs`.`research_paper`" => "research_paper",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`staffs`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`staffs`.`id`" => "id",
		"`staffs`.`name`" => "name",
		"`staffs`.`title`" => "title",
		"`staffs`.`photo`" => "photo",
		"`staffs`.`description`" => "description",
		"`staffs`.`research_paper`" => "research_paper",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`staffs`.`id`" => "ID",
		"`staffs`.`name`" => "Name",
		"`staffs`.`title`" => "Title",
		"`staffs`.`description`" => "Description",
		"`staffs`.`research_paper`" => "Research paper",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`staffs`.`id`" => "id",
		"`staffs`.`name`" => "Name",
		"`staffs`.`title`" => "Title",
		"`staffs`.`description`" => "description",
		"`staffs`.`research_paper`" => "research_paper",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`staffs` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'staffs_view.php';
	$x->TableTitle = 'Staffs';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`staffs`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Name', 'Title', 'Photo', 'Description', 'Research paper', ];
	$x->ColFieldName = ['name', 'title', 'photo', 'description', 'research_paper', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/staffs_templateTV.html';
	$x->SelectedTemplate = 'templates/staffs_templateTVS.html';
	$x->TemplateDV = 'templates/staffs_templateDV.html';
	$x->TemplateDVP = 'templates/staffs_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: staffs_init
	$render = true;
	if(function_exists('staffs_init')) {
		$args = [];
		$render = staffs_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: staffs_header
	$headerCode = '';
	if(function_exists('staffs_header')) {
		$args = [];
		$headerCode = staffs_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: staffs_footer
	$footerCode = '';
	if(function_exists('staffs_footer')) {
		$args = [];
		$footerCode = staffs_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
