<?php
// This script and data application were generated by AppGini 22.14
// Download AppGini for free from https://bigprof.com/appgini/download/

	include_once(__DIR__ . '/lib.php');
	@include_once(__DIR__ . '/hooks/student_achievments.php');
	include_once(__DIR__ . '/student_achievments_dml.php');

	// mm: can the current member access this page?
	$perm = getTablePermissions('student_achievments');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'student_achievments';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`student_achievments`.`id`" => "id",
		"if(CHAR_LENGTH(`student_achievments`.`name`)>40, concat(left(`student_achievments`.`name`,40),' ...'), `student_achievments`.`name`)" => "name",
		"`student_achievments`.`photo`" => "photo",
		"`student_achievments`.`description`" => "description",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`student_achievments`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`student_achievments`.`id`" => "id",
		"`student_achievments`.`name`" => "name",
		"`student_achievments`.`photo`" => "photo",
		"`student_achievments`.`description`" => "description",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`student_achievments`.`id`" => "ID",
		"`student_achievments`.`name`" => "Name",
		"`student_achievments`.`description`" => "Description",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`student_achievments`.`id`" => "id",
		"`student_achievments`.`name`" => "Name",
		"`student_achievments`.`description`" => "description",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`student_achievments` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'student_achievments_view.php';
	$x->TableTitle = 'Student achievments';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`student_achievments`.`id`';

	$x->ColWidth = [150, 150, 150, ];
	$x->ColCaption = ['Name', 'Photo', 'Description', ];
	$x->ColFieldName = ['name', 'photo', 'description', ];
	$x->ColNumber  = [2, 3, 4, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/student_achievments_templateTV.html';
	$x->SelectedTemplate = 'templates/student_achievments_templateTVS.html';
	$x->TemplateDV = 'templates/student_achievments_templateDV.html';
	$x->TemplateDVP = 'templates/student_achievments_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: student_achievments_init
	$render = true;
	if(function_exists('student_achievments_init')) {
		$args = [];
		$render = student_achievments_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: student_achievments_header
	$headerCode = '';
	if(function_exists('student_achievments_header')) {
		$args = [];
		$headerCode = student_achievments_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once(__DIR__ . '/header.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/header.php');
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: student_achievments_footer
	$footerCode = '';
	if(function_exists('student_achievments_footer')) {
		$args = [];
		$footerCode = student_achievments_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once(__DIR__ . '/footer.php'); 
	} else {
		ob_start();
		include_once(__DIR__ . '/footer.php');
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
